version: '3.1'
services:
  db:
    container_name: spring-jwt
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: holaroot
      MYSQL_DATABASE: jwt
      MYSQL_USER: spring
      MYSQL_PASSWORD: holamundo
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql